services:
  - type: web
    name: secure-transfer
    env: docker
    rootDir: secure-transfer
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
  - key: SPRING_DATASOURCE_URL
    sync: false # set this value in the Render dashboard
  - key: SPRING_DATASOURCE_USERNAME
    sync: false
  - key: SPRING_DATASOURCE_PASSWORD
    sync: false

  - type: static
    name: secure-transfer-ui
    rootDir: secure-transfer-ui
    buildCommand: npm ci && npm run build -- --configuration production
    publishPath: dist/secure-transfer-ui/browser # or dist/APP-NAME (check angular.json)
    redirects:
      - source: '/*'
        destination: '/index.html'
        status: 200
